---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sandbox.example.com
  resources:
  - sandboxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sandbox.example.com
  resources:
  - sandboxes/finalizers
  verbs:
  - update
- apiGroups:
  - sandbox.example.com
  resources:
  - sandboxes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sandbox.example.com
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sandbox.example.com
  resources:
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - sandbox.example.com
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
